# Generated by Django 3.1.7 on 2021-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210226_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to='cars'),
            preserve_default=False,
        ),
    ]
