# Generated by Django 3.1.7 on 2021-02-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_year', models.IntegerField(default=0)),
                ('project_finish', models.IntegerField()),
                ('project_appending', models.IntegerField()),
                ('project_not_start', models.IntegerField()),
            ],
        ),
    ]
