# Generated by Django 3.1.7 on 2021-02-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='project_appending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='project_finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='project_not_start',
            field=models.IntegerField(default=0),
        ),
    ]
