# Generated by Django 3.1.7 on 2021-02-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_projets_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projets',
            new_name='Projet',
        ),
    ]
